### ISSUE TITLE
SpringRoll/pixi.js version...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRollTemplate#1]
Would it be possible to put up an updated release on SpringRoll's pixi.js branch? Currently the default template is pulling an old version of the library that, as best as I can tell, seems to be missing `PIXI.utils` used by the PixiDisplay on 0.4.

**Comment by andrewstart** [comment]
We plan to do that once we make the full release of SpringRoll 0.4.0 (soon!).
